- cmd/wallet-sdk-gomobile/README.md
- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/credentialinquirer/credentialinquirer.go
- cmd/wallet-sdk-gomobile/credentialschema/credentialschema.go
- cmd/wallet-sdk-gomobile/credentialsigner/credentialsigner.go
- cmd/wallet-sdk-gomobile/credentialverifier/credentialverifier.go
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- cmd/wallet-sdk-gomobile/kms/kms.go
- cmd/wallet-sdk-gomobile/linkeddomains/linkeddomains.go
- cmd/wallet-sdk-gomobile/openid4ci/openid4ci.go
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp.go
- cmd/wallet-sdk-gomobile/presentationexchange/presentationexchange.go
- cmd/wallet-sdk-gomobile/storage/storage.go
- cmd/wallet-sdk-gomobile/vdr/vdr.go
- cmd/wallet-sdk-gomobile/wallethandle/wallethandle.go
- pkg/api.go
- pkg/doc.go
- scripts/check_lint.sh
Added stubs for various SDK functionality. This is intended as a simple starting point to allow for testing of the gomobile bindings. Real functionality still needs to be added, and the method signatures and comments/documentation still need to be worked on. Many of them are just placeholders.
Some other notes:
* Added a Crypto interface.
* For the storage implementation stubs, I added very basic storage functionality that we can try using while testing out the gomobile bindings.
* Updated linter script to lint the wallet-sdk-gomobile folder.
> feat: Gomobile SDK implementation stubs

- .github/workflows/build.yml
Once Bindings are created, the CI will upload Android/iOS bindings to Github artifacts.
> ci: upload artifacts

- cmd/wallet-sdk-gomobile/didcreator/didcreator.go
- pkg/did/creator/creator.go
- pkg/did/creator/creator_test.go
* Added a TODO in the DID creator Create method docs.
* Updated import statement grouping in creator_test.go file for consistency with the format required by the linter for non-test files.
> docs: Update DID creator method docs, update imports in test file

- .golangci.yml
- cmd/wallet-sdk-gomobile/credentialschema/credentialschema.go
- cmd/wallet-sdk-gomobile/credentialschema/credentialschema_test.go
- cmd/wallet-sdk-gomobile/credentialschema/opts.go
- cmd/wallet-sdk-gomobile/credentialschema/testdata/credential_university_degree.jsonld
- cmd/wallet-sdk-gomobile/credentialschema/testdata/issuer_metadata.json
- cmd/wallet-sdk-gomobile/openid4ci/openid4ci.go
- pkg/credentialschema/credentialdisplay.go
- pkg/credentialschema/credentialschema.go
- pkg/credentialschema/credentialschema_test.go
- pkg/credentialschema/credentialssupported.go
- pkg/credentialschema/issuerdisplay.go
- pkg/credentialschema/models.go
- pkg/credentialschema/opts.go
- pkg/credentialschema/testdata/credential_university_degree.jsonld
- pkg/credentialschema/testdata/issuer_metadata.json
- pkg/credentialschema/testdata/issuer_metadata_without_claims_display.json
- pkg/credentialschema/testdata/unsupported_credential_multiple_subjects.jsonld
- pkg/credentialschema/testdata/unsupported_credential_string_subject.jsonld
- pkg/internal/issuermetadata/issuermetadata.go
- pkg/internal/issuermetadata/issuermetadata_test.go
- pkg/internal/issuermetadata/testdata/sample_issuer_metadata.json
- pkg/memstorage/memstorage_test.go
- pkg/models/issuer/metadata.go
- pkg/openid4ci/models.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
- pkg/openid4ci/testdata/credential_university_degree.jsonld
- pkg/openid4ci/testdata/sample_issuer_metadata.json
* Added a function that allows a caller to resolve VC display data from an issuer's metadata. This can be called directly or at the end of the OpenID4CI flow using the Interaction object.
* Fixed an issue where one of the memstore unit tests would fail intermittently.
* Updated the linter config.
> feat: Resolve function for OpenID4CI display data

- cmd/wallet-sdk-gomobile/openid4ci/interaction.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction_test.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
- test/integration/openid4ci_test.go
* Added an option to specify the user's preferred locale to the OpenID4CI ResolveDisplay method on the Interaction object (I had intended for this to be there before, but missed it)
* Added a constructor for the CredentialRequestOpts type. This allows the Java bindings to create a proper constructor for the type.
> feat: Add locale option to ResolveDisplay, request opts constructor

- demo/app/ios/Podfile.lock
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/main.dart
- demo/app/lib/models/credential_data.dart
- demo/app/lib/models/credential_data_object.dart
- demo/app/lib/services/storage_service.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/views/otp.dart
- demo/app/lib/views/scanner.dart
- demo/app/lib/widgets/credential_card.dart
This pr stores the credential data in the secure storage in the following format 
`{"rawCredential": "data...", 
"credentialDisplay": "data"}`
This format helps us to retrieve the raw credential to send to presentationAuthorize flow.  Issuance flow works as before. Tested
> feat: Update storage and logic to incorporate validate presentation flow

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4ci/OpenID4CI.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4vp/OpenID4VP.kt
- demo/app/ios/Runner/OpenID4VP.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/main.dart
This pr fixes the below: 
Resolve display call was missing in the android 
Updating the ios plugin to accomodate latest ios bindings changes. 
Vp flow is giving `[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NATIVE_ERR, error while process authorization request, Error Domain=go Code=1 "credentials do not satisfy requirements" UserInfo={NSLocalizedDescription=credentials do not satisfy requirements}, null)`. in both android n ios its in progress 
> fix: update android resolve display

- .github/workflows/build.yml
- Update checkout and setup-go actions to v3
- Update macos to v12 as latest tag points to v11
> ci: Update actions to v3 and macos to v12

- go.mod
- pkg/openid4vp/openid4vp.go
- pkg/openid4vp/tokens.go
- Add workaround for PEx to send pathNested
- Add missing fields to id and vp token
> fix: [OpenID4VP]  add aud/nbf/iat/jti values to id_token and vp_token

- test/integration/fixtures/.env
- test/integration/fixtures/profile/profiles.json
Updated the VC server version and the profiles.json file so that it conforms to the format expected by the new server revision.
> feat: Update VC server version

- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/credential/inquirer.go
- cmd/wallet-sdk-gomobile/did/creator.go
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- test/integration/go.mod
- test/integration/go.sum
* Fixed an issue where the CreateDIDOpts KeyType option was not accessible in the mobile bindings due to using an incompatible type
* Made the WrapVerifiablePresentation function private as it's not compatible with gomobile (and didn't need to be exported anyway). It was causing a "skipped function" warning in the bindings.
> fix: Skipped mobile bindings

- cmd/wallet-sdk-gomobile/scripts/build_android_bindings.sh
- cmd/wallet-sdk-gomobile/scripts/build_ios_bindings.sh
- cmd/wallet-sdk-gomobile/scripts/generate_package_list.sh
* Fixed the "Bad substitution" error that happens on Linux by adding a bash shebang to the generate_package_list.sh file
* For consistency with other scripts (though not required for the fix above), also added a bash shebang to the build_android_bindings.sh and build_ios_bindings.sh files as well
* Added a comment explaining the reason for the newline -> space substitution operation in the generate_package_list.sh file
> fix: error in generate_package_list.sh on Linux

- .github/workflows/build.yml
- .github/workflows/release.yml
- Remove v prefix from version to be compliant with semver spec
- Push new releases to trustbloc/wallet-sdk repo
> ci(sdk): push ios bin to trustbloc/wallet-sdk for release job

- .github/workflows/build.yml
- Make scope mandatory
- Add sdk and app as the available scope
> ci(sdk,app): make scope mandatory for conventional commit message

- pkg/common/jwt_signer.go
- test/integration/credentialapi_test.go
test(sdk): integration test for credential signer gomobile API
> fix(sdk): use derived crypto-specific KID for signing in JWSSigner

- cmd/wallet-sdk-gomobile/credential/signer.go
- cmd/wallet-sdk-gomobile/credential/signer_test.go
- test/integration/credentialapi_test.go
> fix(sdk): NewSigner constructor being skipped in mobile bindings

- cmd/wallet-sdk-gomobile/scripts/build_android_bindings.sh
- cmd/wallet-sdk-gomobile/scripts/build_ios_bindings.sh
* Decreased the size of the Android bindings by ~44% (45.3 MB -> 25.5 MB) and decreased the size of the iOS bindings by ~47% (37.5 MB -> 20.1 MB) by adding linker flags that remove unneeded debug information from the generated binaries.
> feat(sdk,app): Smaller mobile bindings

- cmd/wallet-sdk-gomobile/did/creator_test.go
- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/localkms/localkms.go
- cmd/wallet-sdk-gomobile/localkms/localkms_test.go
- cmd/wallet-sdk-gomobile/localkms/memstore.go
- cmd/wallet-sdk-gomobile/localkms/signercreator_test.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction_test.go
- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/ios/Runner/flutterPlugin.swift
- pkg/did/creator/creator_test.go
- pkg/did/creator/ion/ion_test.go
- pkg/localkms/localkms.go
- pkg/localkms/localkms_test.go
- pkg/localkms/provider.go
- pkg/openid4ci/openid4ci_test.go
- test/integration/credentialapi_test.go
- test/integration/openid4ci_test.go
- test/integration/openid4vp_test.go
Fixed an issue with the local KMS implementation that was causing a runtime error when using any store implementation that was injected in from mobile code. Also did some refactoring to bring the local KMS more in line with the other APIs.
> fix(sdk): Runtime error when injecting local KMS store from mobile

- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/openid4ci/resolve.go
- cmd/wallet-sdk-gomobile/openid4ci/resolve_test.go
- cmd/wallet-sdk-gomobile/openid4ci/resolveopts.go
- Simplified the gomobile ResolveDisplay function by removing unneeded options.
- Switched the gomobile ResolveDisplay function to use the VC type introduced previously instead of requiring raw JSON.
- Added documentation.
> feat(sdk): Simplify the ResolveDisplay gomobile function, add docs

- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/api/jsonwebkey.go
- cmd/wallet-sdk-gomobile/api/jsonwebkey_test.go
- cmd/wallet-sdk-gomobile/did/creator.go
- cmd/wallet-sdk-gomobile/did/creator_test.go
- cmd/wallet-sdk-gomobile/did/keywrapper.go
- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/localkms/localkms.go
- cmd/wallet-sdk-gomobile/localkms/localkms_test.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction_test.go
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp_test.go
- pkg/api/api.go
- pkg/common/jwt_signer.go
- pkg/common/jwt_signer_test.go
- pkg/did/creator/creator.go
- pkg/did/creator/creator_test.go
- pkg/did/creator/ion/ion.go
- pkg/did/creator/ion/ion_test.go
- pkg/did/creator/key/key.go
- pkg/localkms/localkms.go
- pkg/localkms/localkms_test.go
- pkg/openid4ci/openid4ci_test.go
- test/integration/openid4ci_test.go
- test/integration/openid4vp_test.go
Allows support for more key types, demonstrates ECDSA P-384 usage.
> feat(sdk): return JWK from KMS APIs instead of raw key.

- .github/workflows/build.yml
- cmd/wallet-sdk-gomobile/openid4ci/interaction.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction_test.go
- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/ios/Runner/flutterPlugin.swift
- pkg/openid4ci/clientconfig.go
- pkg/openid4ci/models.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
- test/integration/fixtures/docker-compose.yml
- test/integration/openid4ci_test.go
- test/integration/openid4vp_test.go
- Enabled VC proof checks during OpenID4CI flow.
- Added an option to disable the aforementioned proof checks. This option is useful for unit tests or debugging purposes.
- Switched integration tests from did:orb to did:ion.
> feat(sdk): Enable VC proof checks during OpenID4CI flow

- pkg/credentialschema/credentialdisplay.go
- pkg/credentialschema/credentialschema_test.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
* Added support for credential offers using the jwt_vc_json-ld credential format.
* Removed format check in display resolver since the VCs passed in there could be of any format (and we don't currently have a way to check what the format is).
> feat(sdk): Improved OpenID4CI credential format handling

- cmd/wallet-sdk-gomobile/display/displaydata.go
- cmd/wallet-sdk-gomobile/display/displaydata_test.go
- pkg/credentialschema/credentialdisplay.go
- pkg/credentialschema/credentialschema_test.go
The display value was sent back as empty for non-masked field. This PR fixes the issue and sends back display value for all claims.
> fix(sdk): display value

- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/openid4ci/interaction.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction_test.go
- pkg/openid4ci/errors.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
* Added an error code that gets returned if credential parsing (a significant operation) fails.
* Updated a potentially misleading error message that gets returned if a user PIN is not set.
* Added a nil check to the request credential methods to ensure that they don't panic if the SDK user fails to pass in the options object. If not set, the method defaults to an empty object (PIN will be empty).
* Updated documentation.
> feat(sdk): Update error handling when requesting credential from issuer

- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/api/credentials_test.go
- cmd/wallet-sdk-gomobile/credential/inquirer.go
- cmd/wallet-sdk-gomobile/credential/inquirer_test.go
- cmd/wallet-sdk-gomobile/credential/memstorage.go
- cmd/wallet-sdk-gomobile/credential/signer.go
- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/openid4ci/interaction.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction_test.go
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp.go
- cmd/wallet-sdk-gomobile/wrapper/documentloaderwrapper.go
- cmd/wallet-sdk-gomobile/wrapper/documentloaderwrapper_test.go
- pkg/credentialschema/credentialschema_test.go
- pkg/openid4ci/clientconfig.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4vp/openid4vp.go
- test/integration/credentialapi_test.go
- test/integration/openid4ci_test.go
- test/integration/openid4vp_test.go
* LD document loaders can now be injected wherever LD document loaders are used.
* Updated default document loader across the SDK to be consistent: now, whenever a document loader is not specified (or is nil), a network-based loader will be used by default.
* Updated docs to described this new default LD loader behaviour.
* Updated unit tests and BDD tests to ensure they never use a network-based loader in order to improve test reliability and performance. Now, tests either have document loading disabled or use pre-loaded contexts. Note that Flutter tests will still use network-based loading for the time being.
closes #160
> feat(sdk): Injectable LD document loader, better test stability

- cmd/wallet-sdk-gomobile/credential/inquirer.go
- cmd/wallet-sdk-gomobile/did/create.go
- cmd/wallet-sdk-gomobile/did/creator.go
- cmd/wallet-sdk-gomobile/did/creatorwithkeyreader.go
- cmd/wallet-sdk-gomobile/did/resolver.go
- cmd/wallet-sdk-gomobile/did/wellknown.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction.go
- cmd/wallet-sdk-gomobile/openid4vp/interaction.go
- cmd/wallet-sdk-gomobile/walleterror/error.go
- cmd/wallet-sdk-gomobile/wrapper/error.go
- cmd/wallet-sdk-gomobile/wrapper/error_test.go
Moved the ToMobileError function from the walleterror package into the wrapper package. This causes it to not be exposed in the bindings since the wrapper package is excluded. This was done since ToMobileError shouldn't be exposed as it's intended to only be used internally.
> fix(sdk)!: Removed the ToMobileError function from mobile bindings

- demo/app/ios/Runner/OpenID4CI.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/assets/issuerAuthFlowConfig.json
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/scenarios/handle_openid_issuance_flow.dart
- demo/app/lib/views/handle_redirect_uri.dart
- demo/app/pubspec.yaml
- This pr also have a logic in place if any issuer don't need scope to function, we will call without  scope method from sdk to get the authorization link. 
- Config file is added to get the auth code flow arguments 
- Removed the scope 1 and scope 2 parameters added array of scope support instead
> feat(app): Add support for multi auth code args from the issuer

- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/api/jsonwebkey.go
- cmd/wallet-sdk-gomobile/api/jsonwebkey_test.go
- cmd/wallet-sdk-gomobile/oauth2/clientmetadata.go
- cmd/wallet-sdk-gomobile/oauth2/clientmetadata_test.go
- cmd/wallet-sdk-gomobile/oauth2/clientregistration.go
- cmd/wallet-sdk-gomobile/oauth2/clientregistration_test.go
- cmd/wallet-sdk-gomobile/oauth2/opts.go
- cmd/wallet-sdk-gomobile/oauth2/registerclientresponse.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction_test.go
- pkg/api/api.go
- pkg/oauth2/clientregistration.go
- pkg/oauth2/clientregistration_test.go
- pkg/oauth2/models.go
- pkg/oauth2/opts.go
- pkg/openid4ci/models.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
Conforms to https://datatracker.ietf.org/doc/html/rfc7591.
Also added new methods on the Interaction object that a caller can use to determine whether an issuer support dynamic client registration (per https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata).
> feat(sdk): OAuth2 Dynamic Client Registration API

- cmd/wallet-sdk-gomobile/oauth2/clientmetadata.go
- cmd/wallet-sdk-gomobile/oauth2/clientmetadata_test.go
- cmd/wallet-sdk-gomobile/oauth2/clientregistration_test.go
- cmd/wallet-sdk-gomobile/oauth2/registerclientresponse.go
- cmd/wallet-sdk-gomobile/openid4ci/grants.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction_test.go
- cmd/wallet-sdk-gomobile/openid4ci/testdata/sample_credential_offer.json
- pkg/oauth2/models.go
- pkg/openid4ci/grants.go
- pkg/openid4ci/models.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
- test/integration/fixtures/.env
- test/integration/fixtures/docker-compose.yml
- test/integration/fixtures/krakend-config/settings/endpoint.json
- test/integration/fixtures/oauth-clients/clients.json
- test/integration/fixtures/profile/profiles.json
- test/integration/openid4ci_test.go
Breaking API change: Updated the dynamic client registration response model to avoid potential confusion between absent values and zero values.
Other changes:
* Made fixes/updated to the JWT claims and header that are sent to the issuer to ensure compliance with the OpenID4CI spec.
* Added an integration test for dynamic client registration. Note that a flag was set for the vc-server instance used in the integration temporarily due to a bug with the "aud" and "iat" claim checks. This flag will be removed once the bug has been fixed and the vc-server version here updated.
* Added methods to the interaction object which will allow a user to get the issuer_state value, and also added the ability to set an issuer_state value in the client metadata object sent to the dynamic client …
> fix(sdk)!: Fixed JWT params sent to issuer, added dynamic client reg test

- pkg/openid4ci/errors.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
- test/integration/fixtures/.env
- test/integration/fixtures/docker-compose.yml
With recent fixes to VCS (vc-server), state-checking during the OpenID4CI authorization-code flow now work. Also, the JWT claims sent to the credential endpoint are now validated correctly, so the temporary flag we used during the integration tests is no longer needed.
> fix(sdk): Enable state-checking and remove vc-server flag

- cmd/wallet-sdk-gomobile/oauth2/clientmetadata.go
- cmd/wallet-sdk-gomobile/oauth2/clientmetadata_test.go
- cmd/wallet-sdk-gomobile/oauth2/clientregistration_test.go
- cmd/wallet-sdk-gomobile/oauth2/registerclientresponse.go
- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4ci/OpenID4CI.kt
- demo/app/ios/Runner/OpenID4CI.swift
- demo/app/ios/Runner/flutterPlugin.swift
- pkg/oauth2/clientregistration_test.go
- pkg/oauth2/models.go
- test/integration/openid4ci_test.go
Breaking change: Changes to names and methods in dynamic client registration API. See below for details.
* In the Gomobile API, changed the scopes parameter type to a StringArray. Internally, it will be converted to the space-separated string that is required by the dynamic client registration spec, so this way the user of the SDK doesn't have to deal with splitting/parse spaces. Also, changed the method names from `scope` to `scopes`.
* In the Gomobile API, removed the hasClientMetadata method from the response object. Response objects don't actually have a nested clientMetadata object - the ClientMetadata object is just an abstraction here to make code cleaner and allow for reuse - so it doesn't make sense to ask if the object exists or not.
* For the response object, switched it from …
> feat(sdk)!: Improvements to dynamic client registration API

- demo/app/lib/models/connect_issuer_config_value.dart
`dart:ffi` is specifically designed for native code interoperability in Flutter mobile apps, but does not work in web. Need to find a solution to avoid break the web app.
> fix(app): removed ffi lib to unblock web app

- cmd/wallet-sdk-gomobile/openid4ci/createauthorizationurlopts.go
- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteraction.go
- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteraction_test.go
- cmd/wallet-sdk-gomobile/openid4ci/walletinitiatedinteraction.go
- cmd/wallet-sdk-gomobile/openid4ci/walletinitiatedinteraction_test.go
- pkg/openid4ci/createauthorizationurlopts.go
- pkg/openid4ci/interaction.go
- pkg/openid4ci/issuerinitiatedinteraction.go
- pkg/openid4ci/issuerinitiatedinteraction_test.go
- pkg/openid4ci/walletinitiatedinteraction.go
- pkg/openid4ci/walletinitiatedinteraction_test.go
* Added an option to set the issuer state value when creating an authorization URL during the OpenID4CI flow.
* Fixed a bug where the credential type and formats were not being set in the credential request sent to the issuer during the wallet-initiated OpenID4CI flow.
> feat(sdk): Option to set issuer state when creating authorization URL

- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteraction_test.go
- cmd/wallet-sdk-gomobile/openid4ci/walletinitiatedinteraction_test.go
- cmd/wallet-sdk-gomobile/walleterror/error.go
- cmd/wallet-sdk-gomobile/wrapper/error.go
- cmd/wallet-sdk-gomobile/wrapper/error_test.go
This replaces the solution introduced in my previous commit where I added a "Full" field to the mobile error to give the caller a way to get the complete error message. This new solution allows the higher-level error messages to not be lost and also not require the caller to examine the parsed error message any differently.
> feat(sdk): Merge higher-level errors into mobile error details field

- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteraction.go
- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteraction_test.go
- cmd/wallet-sdk-gomobile/walleterror/error.go
- cmd/wallet-sdk-gomobile/wrapper/error.go
- cmd/wallet-sdk-gomobile/wrapper/error_test.go
- pkg/openid4ci/issuerinitiatedinteraction.go
- pkg/openid4vp/errors.go
- pkg/openid4vp/openid4vp.go
- pkg/openid4vp/openid4vp_test.go
* Added parsing for OpenID4VP error responses per the spec + new error codes.
*  For consistency, replaced one of the existing OpenID4VP error codes with the new "invalid SDK usage" error code type introduced in the OpenID4CI error handling commit.
* Previously, when errors without error type info were consumed in an app using the gomobile bindings, the default error code and category would differ depending on which layer the error processing was done (would be either GNR2-000/GENERAL_ERROR or UKN2-000/UNEXPECTED_ERROR). I've updated it so that we use the same error code and category in both places. I chose "OTHER_ERROR" for the category to try to be more descriptive/accurate of what the category is.
> feat(sdk): OpenID4VP error response parsing

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/views/credential_shared.dart
- demo/app/lib/views/custom_error.dart
- demo/app/lib/views/otp.dart
- demo/app/lib/wallet_sdk/wallet_sdk_mobile.dart
- demo/app/lib/wallet_sdk/wallet_sdk_model.dart
- Used wallet sdk parsed error api to get the parsed details and category 
- Based on  parsed Category (INVALID_GRANT) a messaging is shown to the user **"Oops! Something went wrong! 
Try re-entering the pin or scan the new QR code."** 
- For the other categories we will show what ever is been sent in the details by parsed method. 
- If user has entered wrong pin they can try re-entering or restart the operation as per the messaging. 
- If pin was wrong and user re-entered the right pin, user will be redirected to credential preview screen 
Things to fix: 
- Add a loader once the user hit the submit or renter button #509 
- Make the button submit/ Cancel button fix to the bottom right now they drag further to the Botton  when error widget appears #510
> feat(app): Update the invalid pin error handling scenario

- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteraction_test.go
- pkg/openid4ci/errors.go
- pkg/openid4ci/interaction.go
- pkg/openid4ci/issuerinitiatedinteraction.go
- pkg/openid4ci/issuerinitiatedinteraction_test.go
* When instantiating an issuer-initiated interaction object, we now enforce that it must use the openid-credential-offer scheme.
* Also fixed a misplaced comment.
> feat(sdk): Issuance URI scheme validation

- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteraction.go
- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteraction_test.go
- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteractionalias.go
- cmd/wallet-sdk-gomobile/openid4ci/issuermetadata.go
- cmd/wallet-sdk-gomobile/openid4ci/issuermetadata_test.go
- cmd/wallet-sdk-gomobile/openid4ci/localizedcredentialdisplay.go
- cmd/wallet-sdk-gomobile/openid4ci/localizedissuerdisplay.go
- cmd/wallet-sdk-gomobile/openid4ci/logo.go
- cmd/wallet-sdk-gomobile/openid4ci/supportedcredential.go
- cmd/wallet-sdk-gomobile/openid4ci/testdata/sample_issuer_metadata.json
- cmd/wallet-sdk-gomobile/openid4ci/walletinitiatedinteraction.go
- cmd/wallet-sdk-gomobile/openid4ci/walletinitiatedinteraction_test.go
- demo/app/ios/Runner/WalletInitiatedOpenID4CI.swift
- pkg/credentialschema/credentialdisplay.go
- pkg/credentialschema/credentialschema.go
- pkg/credentialschema/credentialschema_test.go
- pkg/credentialschema/issuerdisplay.go
- pkg/models/issuer/metadata.go
- pkg/openid4ci/interaction.go
- pkg/openid4ci/issuerinitiatedinteraction.go
- pkg/openid4ci/walletinitiatedinteraction.go
Breaking changes:
* The new issuerMetadata method takes the existing supportedCredentials method and extends upon it with additional functionality. As such, there's no longer any need for the supportedCredentials method and so it has been removed.
* Some of the field/object names in the Go API were changed to make them more clear.
Note that the claim display data in the issuer metadata object is not exposed via Gomobile currently.
> feat(sdk)!: Ability to get issuer metadata in mobile bindings

- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/openid4ci/createauthorizationurlopts.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction.go
- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteraction.go
- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteraction_test.go
- cmd/wallet-sdk-gomobile/openid4ci/walletinitiatedinteraction.go
- pkg/openid4ci/createauthorizationurlopts.go
- pkg/openid4ci/interaction.go
- pkg/openid4ci/issuerinitiatedinteraction.go
- pkg/openid4ci/issuerinitiatedinteraction_test.go
- pkg/openid4ci/walletinitiatedinteraction.go
* Support for the OAuth Discoverable Client ID Scheme described in https://mattrglobal.github.io/draft-looker-oauth-client-id-scheme/draft-looker-oauth-client-id-scheme.html.
* Added documentation for how to use this scheme with Wallet-SDK.
* Updated documentation for the other methods of getting/providing a client ID.
* Eliminated some code duplication by doing some refactoring.
> feat(sdk): Support for the OAuth Discoverable Client ID Scheme

- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/walleterror/error.go
- cmd/wallet-sdk-gomobile/wrapper/error.go
- cmd/wallet-sdk-gomobile/wrapper/error_test.go
- pkg/openid4vp/errors.go
- pkg/openid4vp/openid4vp.go
- pkg/openid4vp/openid4vp_test.go
- pkg/walleterror/walleterror.go
- pkg/walleterror/walleterror_test.go
* Added a new "message" field for wallet errors. Currently only used for MS Entra error responses.
* Updated docs.
* Added a new unit test for the invalid SDK usage error type.
> feat(sdk): Added a new message field to errors

- cmd/wallet-sdk-gomobile/docs/packages.md
- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-js/docs/usage.md
The docs have a "last updated" line containing the date and commit hash of their last update. There are a few problems with this:
* It's virtually impossible to specify the hash of the commit you're working on, since the commit hash relies on the content of your commit. Therefore the best you can do is list a previous commit hash. If you wanted to add docs for some new code you added, then you'd have to commit the code first (to get the hash), and then add the docs afterward, which is inconvenient.
* It's easy to forget to update the date and hard to guarantee the date will match when the pull request actually gets merged in.
For these reasons, and since Git can already tell you the last commit that a file was modified in anyway, it makes sense to simply remove these lines.
> docs(sdk): Remove "last updated" lines

- .golangci.yml
- cmd/wallet-sdk-gomobile/localkms/localkms.go
- cmd/wallet-sdk-gomobile/openid4ci/issuerinitiatedinteraction.go
- cmd/wallet-sdk-gomobile/openid4ci/walletinitiatedinteraction.go
- cmd/wallet-sdk-gomobile/openid4vp/interaction_test.go
- cmd/wallet-sdk-gomobile/verifiable/parsecredential_test.go
- cmd/wallet-sdk-gomobile/wrapper/httpclient_test.go
- cmd/wallet-sdk-gomobile/wrapper/resolverwrapper_test.go
- pkg/common/jwt_signer_test.go
- pkg/credentialquery/credentialquery_test.go
- pkg/internal/mock/httpclient.go
- pkg/openid4ci/issuerinitiatedinteraction_test.go
- pkg/openid4vp/openid4vp.go
- pkg/openid4vp/openid4vp_test.go
- scripts/check_lint.sh
Some new dependencies from aries-framework-go that we will need have some incompatibilities with the older linter version we're using. Updating the linter fixes this. This commit also updates code to comply with new rules in the linter (except for depguard, which has been added to the list of exceptions for now as it requires more consideration).
> fix(sdk): Update linter

- .github/workflows/build.yml
WASM tests have been temporarily disabled to due compatibility issues with Go 1.21.
> chore(sdk): Disable WASM integration tests (temporary)

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/scenarios/handle_openid_vp_flow.dart
Edge case for when both type and schemas are missing will be addresses in  #575 
> feat(app): Detect type of supported schemas when credentials are not found

- demo/app/lib/views/issuance_preview.dart
- demo/app/lib/views/supported_credentials_list.dart
- demo/app/lib/wallet_sdk/wallet_sdk_js.dart
- demo/app/lib/wallet_sdk/wallet_sdk_model.dart
> fix(app): fixed issuance preview screen in web

- demo/app/lib/models/store_credential_data.dart
- demo/app/lib/scenarios/handle_openid_vp_flow.dart
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/wallet_sdk/wallet_sdk_js.dart
> fix(app): fixed data handling logic in verification flow for web

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/ios/Runner/OpenID4CI.swift
- demo/app/ios/Runner/WalletSDK.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/scenarios/handle_openid_issuance_flow.dart
- demo/app/lib/views/custom_error.dart
If you enter any random string in the qr code scanning text field in the simulator, that is handled now as well. 
> fix(app): Add exception handling for the QR code scanning process

- cmd/wallet-sdk-gomobile/didkey/didkey.go
- cmd/wallet-sdk-gomobile/didkey/didkey_test.go
- pkg/did/creator/key/key.go
- pkg/did/creator/key/key_test.go
- test/integration/pkg/helpers/openid4ci.go
Added a new function for creating did:key DIDs. This new standalone function directly takes in a key instead of a keyWriter or keyReader, giving the caller more flexibility in terms of key management. It also minimizes input parameters to only what's required, helping reduce confusion caused by unused parameters.
> feat(sdk): Improved did:key create function

- cmd/wallet-sdk-gomobile/didjwk/didjwk.go
- cmd/wallet-sdk-gomobile/didjwk/didjwk_test.go
- pkg/did/creator/jwk/jwk.go
- pkg/did/creator/jwk/jwk_test.go
- pkg/did/creator/key/key_test.go
- test/integration/openid4ci_test.go
- test/integration/pkg/helpers/openid4ci.go
Added a new function for creating did:jwk DIDs. This new standalone function directly takes in a key instead of a keyWriter or keyReader, giving the caller more flexibility in terms of key management. It also minimizes input parameters to only what's required, helping reduce confusion caused by unused parameters.
> feat(sdk): Improved did:jwk create function

- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/docs/bestpractices.md
- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/localkms/localkms.go
- cmd/wallet-sdk-js/jsinterop/agent.go
- cmd/wallet-sdk-js/src/index.js
- cmd/wallet-sdk-js/walletsdk/agent.go
- demo/app/android/app/src/androidTest/kotlin/integration_test.kt
- demo/app/android/app/src/main/kotlin/walletsdk/WalletSDK.kt
- demo/app/integration_test/openid4ci_test.dart
- demo/app/ios/Runner/Tests/IntegrationTest.swift
- demo/app/ios/Runner/WalletSDK.swift
- pkg/did/creator/jwk/jwk.go
- pkg/did/creator/key/key.go
- test/integration/credentialapi_test.go
- test/integration/pkg/helpers/openid4ci.go
- test/integration/pkg/helpers/openid4vp.go
* Updated the demo apps to use the new DID creation patterns.
* Updated the JS bindings to use the new DID creation patterns.
* Updated docs.
* Fixed an issue where the P256 key type string constant wasn't accessible from the mobile bindings.
* Other minor refactoring.
> refactor(app): Use new DID creation patterns; updated docs

- demo/app/lib/scenarios/handle_openid_vp_flow.dart
Current Behaviour: While selecting one from many credentials we were showing all stored credentials
Expected Behaviour: It should show only the list of credentials which matches the submission not all.
> fix(app): Show the list of credentials which matches the submission

- demo/app/ios/Runner/OpenID4VP.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/assets/customScopes.json
- demo/app/lib/services/config_service.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/views/presentation_preview_multi_cred_radio.dart
- demo/app/lib/wallet_sdk/wallet_sdk_mobile.dart
- demo/app/pubspec.yaml
> feat(app): Add support for custom scope in verfication flow

- pkg/openid4vp/openid4vp.go
Trust info is verfied and in the logs : 
evaulating the presention response {"allowed":true,"payload":{}}
> feat(app): Handle _sd credential subjects in the presentation flow

- pkg/credentialschema/credentialdisplay.go
The code throws panic when thre is no display data. Added length check before fecthing the first item.
> fix(sdk): check display length
