- .github/workflows/sonar.yml
> ci: sonar configuration

- demo/app/.eslintrc.js
- demo/app/public/index.html
- demo/app/src/App.vue
- demo/app/src/components/ExploreContainer.vue
- demo/app/src/composables/useCamera.ts
- demo/app/src/main.ts
- demo/app/src/router/index.ts
- demo/app/src/shims-vue.d.ts
- demo/app/src/views/Tab1.vue
- demo/app/src/views/Tab2.vue
- demo/app/src/views/Tab3.vue
- demo/app/src/views/Tabs.vue
> chore: add license header

- README.md
- demo/app/README.md
> docs: Update README

- README.md
> docs: fix README grammar

- .github/workflows/build.yml
- build.gradle
- ci/version_var.sh
> ci: publish vc-wallet-sdk android library

- ci/version_var.sh
> fix: [test] update snapshot repo to point to main repo

- ci/version_var.sh
> ci: make SNAPSHOT all caps

- ci/version_var.sh
> ci: Update snapshot repo

- README.md
> docs: Android package details

- cmd/wallet-sdk-gomobile/Makefile
- cmd/wallet-sdk-gomobile/README.md
> chore: Add Android java pkg name

- demo/app/ios/Runner/AppDelegate.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/Dashboard.dart
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/demo_platform_interface.dart
- demo/app/lib/main.dart
- On Sign in button create did method of the wallet-sdk is invoked (video shows created did printed in the console) 
- Dashboard has bottom navigation bar as discussed for the following actions - Settings, Scan QR code and credentials. 
- This change was tested against the drafted pr of the derek to create did 
closes #39 #40 
https://user-images.githubusercontent.com/7862595/199167825-0bda35b2-b8fd-44ab-8150-7d7fcee47b0c.mp4
> feat: Sign In page (Registration) and dashboard Page

- .gitignore
> chore: Add android/iOS binaries to gitignore

- demo/app/ios/Podfile
- demo/app/ios/Podfile.lock
- demo/app/ios/Runner/Info.plist
- demo/app/lib/Dashboard.dart
- demo/app/lib/Scanner.dart
- demo/app/lib/main.dart
- demo/app/pubspec.lock
- demo/app/pubspec.yaml
https://user-images.githubusercontent.com/7862595/200936259-8bc50af4-a04b-4150-883b-81226eb76832.mp4
https://user-images.githubusercontent.com/7862595/200936760-83baa44d-37ff-4a0b-9257-b92465b6fc1d.mp4
https://user-images.githubusercontent.com/7862595/200770368-523332a9-d34a-4c53-804c-79fce84cbff5.mp4
> feat: camera qr code scanner

- demo/app/lib/assets/images/logo.png
- demo/app/lib/main.dart
- demo/app/pubspec.yaml
Will make more ui changes as we progress 
> feat: Removed password and ui changes to sign in page 

- cmd/wallet-sdk-gomobile/didcreator/didcreator.go
- scripts/check_unit.sh
> fix: Include wallet-sdk-gomobile in code coverage, fix DID creator bugs

- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- cmd/wallet-sdk-gomobile/openid4ci/openid4ci.go
- cmd/wallet-sdk-gomobile/openid4ci/openid4ci_test.go
- go.mod
- go.sum
- pkg/openid4ci/models.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
Actual implementations of the Authorize and RequestCredential methods to come later.
> feat: OpenID4CI Skeleton

- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/credential_preview.dart
- demo/app/lib/dashboard.dart
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/otp.dart
- demo/app/lib/scanner.dart
closes #63
Credential is received from the walletsdk request credential  framework
> feat: Integration of walletsdk open id vc flow ios

- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/didcreator/didcreator_test.go
- cmd/wallet-sdk-gomobile/didcreator/keywrapper.go
- cmd/wallet-sdk-gomobile/localkms/localkms.go
- cmd/wallet-sdk-gomobile/localkms/localkms_test.go
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp.go
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp_test.go
- pkg/api/api.go
- pkg/common/keyresolver.go
- pkg/did/creator/creator_test.go
- pkg/localkms/localkms.go
- pkg/localkms/localkms_test.go
- pkg/openid4vp/openid4vp.go
- pkg/openid4vp/openid4vp_test.go
> fix: pr fixes minor issues from previous openid4vp pr.

- .golangci.yml
- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/didcreator/keywrapper.go
- cmd/wallet-sdk-gomobile/localkms/localkms.go
- cmd/wallet-sdk-gomobile/localkms/localkms_test.go
- cmd/wallet-sdk-gomobile/openid4ci/openid4ci.go
- cmd/wallet-sdk-gomobile/openid4ci/openid4ci_test.go
- pkg/openid4ci/models.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
Implemented the OpenID4CI methods. Note that JWT signing will come in a future commit.
> feat: OpenID4CI Implementation

- demo/app/android/app/src/main/AndroidManifest.xml
- demo/app/android/app/src/main/java/dev/trustbloc/wallet/MainActivity.java
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/otp.dart
- demo/app/lib/scanner.dart
- demo/app/pubspec.lock
- demo/app/pubspec.yaml
closes #68 
IOS Video
https://user-images.githubusercontent.com/7862595/202269398-d4a3f65a-9c03-404e-a8d8-e06bff9cc0f8.mp4
Android Video
https://user-images.githubusercontent.com/7862595/202268774-d017febb-ce25-4cf2-b097-2b079342ea71.mp4
> feat: Integrate wallet-sdk changes with andoid plugin

- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/views/otp.dart
This is the initial cut will refine more in the upcoming prs 
#86  Background color and logo need to be taken into consideration separately as colors data which we are expecting flutter is color widget are not rendering those values
> feat: Credential Preview screen

- cmd/utilities/go.mod
- cmd/utilities/go.sum
- cmd/utilities/gomobilewrappers/resolverwrapper.go
- cmd/utilities/gomobilewrappers/resolverwrapper_test.go
- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- cmd/wallet-sdk-gomobile/localkms/localkms.go
- cmd/wallet-sdk-gomobile/localkms/localkms_test.go
- cmd/wallet-sdk-gomobile/localkms/signercreator.go
- cmd/wallet-sdk-gomobile/openid4ci/openid4ci.go
- cmd/wallet-sdk-gomobile/openid4ci/openid4ci_test.go
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp.go
- go.mod
- go.sum
- pkg/localkms/localkms.go
- pkg/localkms/localkms_test.go
- pkg/localkms/provider.go
- pkg/openid4ci/clientconfig.go
- pkg/openid4ci/models.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
> feat: JWT Signing in OpenID4CI flow

- demo/app/lib/main.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/views/dashboard.dart
- pkg/openid4ci/models.go
- pkg/openid4ci/openid4ci.go
- Register for application as user1
- Save Credential
- Dashboard shows 1 credential
- Signout as user1
- Register for application as user2
- No credentials should be visible in dashboard
- Signout as user2
- SignIn as user1
- Dashboard should show 1 credential
https://user-images.githubusercontent.com/7862595/205852266-78210f92-043d-4f13-8f39-19629b74126d.mp4
> feat: Add option to save credential based on the registered username

- cmd/wallet-sdk-gomobile/api/credentials.go
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- cmd/wallet-sdk-gomobile/openid4ci/openid4ci.go
- test/integration/go.mod
- test/integration/go.sum
- test/integration/openid4ci_test.go
- test/integration/openid4vp_test.go
> feat: typed credential and credential array.

- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/api/credentials.go
- cmd/wallet-sdk-gomobile/api/credentials_test.go
- cmd/wallet-sdk-gomobile/api/diddocresolution.go
- cmd/wallet-sdk-gomobile/api/diddocresolution_test.go
- cmd/wallet-sdk-gomobile/api/testdata/credential_drivers_licence.jsonld
- cmd/wallet-sdk-gomobile/api/testdata/credential_university_degree.jsonld
- cmd/wallet-sdk-gomobile/api/testdata/valid_doc_resolution.jsonld
- cmd/wallet-sdk-gomobile/didcreator/didcreator.go
Added a custom type for the DID doc resolution object returned by the DID creator's create method. This custom type will make it easier for mobile code to extract the ID from the object.
> feat: DID doc resolution type for mobile

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4ci/OpenID4CI.kt
https://user-images.githubusercontent.com/7862595/207198972-af6a3190-834e-4ac1-a1f9-f78d04046924.mp4
> fix: Call to resolve display is missing after request credential

- demo/app/ios/Runner/OpenID4VP.swift
- demo/app/ios/Runner/flutterPlugin.swift
https://user-images.githubusercontent.com/7862595/207234424-677e6c5e-9206-426c-a8d2-3627ca1e6e27.mp4
> refactor: update sdk type names

- demo/app/lib/widgets/credential_card.dart
Name in the overview is being sent as urn need to touch base with backend team to get right value 
https://user-images.githubusercontent.com/7862595/207263808-f184607d-8fb7-42cd-b9cc-c8d03904b012.MP4
> feat: Update credential list to show details in nice format

- demo/app/ios/Runner/flutterPlugin.swift
> fix: iOS build with changes from wallet-sdk

- README.md
- cmd/wallet-sdk-gomobile/README.md
- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/localkms/localkms.go
- pkg/localkms/localkms.go
> docs: Mobile bindings usage

- cmd/wallet-sdk-gomobile/api/diddocresolution.go
- cmd/wallet-sdk-gomobile/api/diddocresolution_test.go
- cmd/wallet-sdk-gomobile/api/testdata/valid_doc_resolution.jsonld
- cmd/wallet-sdk-gomobile/credential/inquirer.go
- cmd/wallet-sdk-gomobile/credential/inquirer_test.go
- test/integration/go.mod
- test/integration/go.sum
- test/integration/openid4vp_test.go
> feat: openid4vp integration test.

- cmd/wallet-sdk-gomobile/did/resolver.go
- cmd/wallet-sdk-gomobile/did/resolver_test.go
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- go.mod
- go.sum
- pkg/did/resolver/resolver.go
- pkg/did/resolver/resolver_test.go
- pkg/openid4ci/openid4ci_test.go
- test/integration/go.mod
- test/integration/go.sum
- test/integration/openid4ci_test.go
> feat: add ion longform resolver to sdk did resolver

- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/views/otp.dart
https://user-images.githubusercontent.com/7862595/207525416-b31103f6-97c6-4c35-8149-63012ac3c4e7.mp4
closes #99
> fix: Fix the app crash when incorrect pin is entered

- test/integration/openid4vp_test.go
> fix: integration test compilation error

- cmd/wallet-sdk-gomobile/did/resolver.go
- cmd/wallet-sdk-gomobile/did/resolver_test.go
- pkg/did/resolver/resolver.go
- pkg/did/resolver/resolver_test.go
- pkg/openid4ci/openid4ci_test.go
- test/integration/openid4ci_test.go
- test/integration/openid4vp_test.go
Allows optional integration with a did resolution server.
> feat: add httpbinding support to did resolver

- cmd/wallet-sdk-gomobile/credential/memstorage.go
- cmd/wallet-sdk-gomobile/ld/ld.go
- cmd/wallet-sdk-gomobile/openid4ci/resolveopts.go
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp.go
- pkg/common/httpclient.go
- pkg/credentialschema/credentialschema_test.go
- pkg/did/resolver/resolver.go
- pkg/openid4ci/openid4ci.go
> chore: consolidate uses of http DefaultClient or empty Client

- cmd/utilities/go.mod
- cmd/utilities/go.sum
- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/did/creator.go
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- go.mod
- go.sum
- pkg/did/creator/creator.go
- pkg/did/creator/creator_test.go
- test/integration/go.mod
- test/integration/go.sum
> fix: ion longform did creator uses jwk for all key types

- test/integration/fixtures/docker-compose.yml
> test: remove unused docker containers (metrics and vp-store)

- cmd/wallet-sdk-gomobile/credential/inquirer.go
- pkg/credentialquery/credentialquery.go
- test/integration/fixtures/profile/profiles.json
> fix: disable schema validation for CreateVP.

- demo/app/ios/Runner/OpenID4VP.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/views/credential_shared.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/views/scanner.dart
https://user-images.githubusercontent.com/7862595/209066292-d4a0c320-6bee-4c86-8ec4-216ffb4c7182.mp4
https://user-images.githubusercontent.com/7862595/209066314-653edbc4-7580-49f9-a60f-394e196a8af6.mp4
> feat: Update presentation Preview and credential shared screen

- demo/app/ios/Runner/OpenID4VP.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/views/credential_shared.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/views/scanner.dart
https://user-images.githubusercontent.com/7862595/209178679-d11e22e9-f779-4812-a96d-b9db145fafa3.mp4
> fix: Update ios plugin and flutter logic to fix the present credential call

- .github/workflows/build.yml
- Makefile
- test/integration/fixtures/docker-compose.yml
- test/integration/fixtures/profile/profiles.json
> feat: improve flutter intergration test ci speed.

- .github/workflows/build.yml
> feat: cache build files to improve flutter ci performance.

- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/main.dart
- demo/app/lib/models/store_credential_data.dart
- demo/app/lib/services/storage_service.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/views/credential_shared.dart
- demo/app/lib/views/dashboard.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/views/scanner.dart
- demo/app/lib/views/settings.dart
- demo/app/pubspec.lock
- demo/app/pubspec.yaml
https://user-images.githubusercontent.com/7862595/209425284-f0f0bc04-f9ac-4e14-a511-060fd8b8c701.MP4
> feat: Add settings page in the app and update createdid logic

- demo/app/lib/views/settings.dart
> fix: Move getuserdetail function to initstate

- test/integration/fixtures/profile/profiles.json
- test/integration/go.mod
- test/integration/openid4ci_test.go
- test/integration/openid4vp_test.go
Add table test to validate different DID Method combinations
> test: Add table tests to validate different DID Method combinations

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/integration_test/openid4ci_test.dart
- demo/app/ios/Podfile.lock
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/main.dart
This will help pass different methods from integration tests as well as the app without changing the plugin
> refactor: [ref-app] pass did method type as argument to flutter plugins

- demo/app/lib/assets/images/background.png
- demo/app/lib/assets/images/glow.png
- demo/app/lib/assets/images/logo.png
- demo/app/lib/main.dart
- demo/app/lib/widgets/primary_button.dart
- demo/app/lib/widgets/primary_input_field.dart
- demo/app/pubspec.lock
- demo/app/pubspec.yaml
Added resuable button and input text component and updated sign in page 
**Figma design page** 
====================================
**Implmented design page** 
> feat: Implement update sign up ui

- .github/workflows/build.yml
- Makefile
- scripts/flutter_test.sh
- test/integration/cli/main.go
- Add flutter iOS integration test
- Remove github actions job for generating iOS/Android binding as these are covered in flutter integration test
- Update Makefile to support both iOS and android tests
> test: [iOS] flutter integration test

- demo/app/lib/assets/images/genericCredential.png
- demo/app/lib/main.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/views/dashboard.dart
- demo/app/lib/widgets/common_appbar.dart
- demo/app/lib/widgets/credential_card.dart
- demo/app/pubspec.yaml
https://user-images.githubusercontent.com/7862595/210935997-8fc8c8a5-8c70-4097-850d-2d3755a0b271.MP4
closes #148 
TODO: Credential list will be updated in the followup task
> feat: Implement updated ui for dashboard view 

- cmd/wallet-sdk-gomobile/did/creator.go
- cmd/wallet-sdk-gomobile/did/creator_test.go
> fix: Nil pointer exception when CreateDIDOpts object not provided

- demo/app/lib/main.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/views/dashboard.dart
- demo/app/lib/views/scanner.dart
- demo/app/lib/widgets/common_logo_appbar.dart
- demo/app/lib/widgets/common_title_appbar.dart
> feat: Update scanner UI and decode base64 image to actual image

- demo/app/ios/Runner.xcodeproj/project.pbxproj
> chore: iOS Bundle identifier update to dev.trustbloc.wallet

- cmd/wallet-sdk-gomobile/credential/memstorage.go
- demo/app/README.md
- pkg/common/jwt_signer.go
- pkg/credentialquery/credentialquery.go
- pkg/did/creator/creator.go
- pkg/internal/issuermetadata/issuermetadata.go
- pkg/localkms/localkms.go
- pkg/openid4ci/clientconfig.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4vp/openid4vp.go
> docs: Add github issues to TODOs

- .github/workflows/build.yml
- .github/workflows/release.yml
> ci: Update Android SDK publish job name

- demo/app/lib/assets/images/credLogo.png
- demo/app/lib/assets/images/verified.png
- demo/app/lib/main.dart
- demo/app/lib/views/otp.dart
- demo/app/lib/views/scanner.dart
- demo/app/lib/widgets/common_title_appbar.dart
- demo/app/lib/widgets/primary_button.dart
- demo/app/lib/widgets/primary_input_field.dart
- demo/app/pubspec.yaml
https://user-images.githubusercontent.com/7862595/212127273-f610ce40-fe5b-4331-ae30-c0d3bf90e286.mp4
TODO- #174  is added to read the issuer metadata dynamically 
closes #172 
> feat: Implement OTP Screen UI 

- .github/workflows/build.yml
- .github/workflows/release.yml
GitHub actions job to run during commit and release actions to psuh updated package.swift file along with xcframework binary
> ci(sdk): ios xcframework release

- .github/workflows/build.yml
> ci(sdk): fix ios ci-cd target repo

- README.md
> docs(sdk): add iOS swift pm and update android maven pm reference

- .github/workflows/build.yml
- .github/workflows/release.yml
> ci(sdk): ios release job branch fix + snapshot version fix

- cmd/wallet-sdk-gomobile/credential/signer.go
- cmd/wallet-sdk-gomobile/credential/signer_test.go
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp_test.go
- go.mod
- go.sum
- pkg/common/jwt_signer.go
- pkg/common/jwt_signer_test.go
- pkg/credentialsigner/signer.go
- pkg/credentialsigner/signer_test.go
- pkg/models/verificationmethod.go
- test/integration/go.mod
- test/integration/go.sum
> feat: issue api for self-issued JWT credentials

- demo/app/lib/assets/images/errorVector.png
- demo/app/lib/views/otp.dart
- demo/app/pubspec.yaml
https://user-images.githubusercontent.com/7862595/212263958-7b89c2de-c17d-4ded-aa51-cdecbe6f22d2.mov
> fix: Update error handling for entering incorrect pin

- demo/app/lib/views/credential_details.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/views/otp.dart
- demo/app/lib/widgets/credential_card.dart
- demo/app/pubspec.lock
- demo/app/pubspec.yaml
https://user-images.githubusercontent.com/7862595/213070171-b6c80e21-75a7-4f8b-9383-72b5caa7fef0.mov
> fix(app):  Implement Credential Detail screen UI

- demo/app/integration_test/openid4ci_test.dart
- scripts/flutter_test.sh
- test/integration/cli/main.go
> test(app): update flutter test to pass DID method type + cli to pass profileID

- test/integration/openid4vp_test.go
> test(sdk): add wallet did:key testcase to openid4vp integration test

- pkg/localkms/errors.go
- pkg/localkms/localkms.go
- pkg/localkms/localkms_test.go
> feat(sdk): kms error model.

- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- go.mod
- go.sum
- pkg/did/creator/creator.go
- pkg/did/creator/creator_test.go
- pkg/did/creator/jwk/jwk.go
- pkg/did/creator/jwk/jwk_test.go
- pkg/did/errors.go
- test/integration/go.mod
- test/integration/go.sum
> feat(sdk): DID creator supports did:jwk

- cmd/wallet-sdk-gomobile/credential/inquirer.go
- cmd/wallet-sdk-gomobile/credential/signer.go
- cmd/wallet-sdk-gomobile/openid4ci/resolveopts.go
- cmd/wallet-sdk-gomobile/wrapper/credentialreader.go
- cmd/wallet-sdk-gomobile/wrapper/credentialreader_test.go
> refactor(sdk): Remove unused doc loader from cred reader

- pkg/did/resolver/resolver.go
- pkg/did/resolver/resolver_test.go
- test/integration/openid4vp_test.go
test(sdk): add did:jwk test case to openid4vp integration test
> feat(sdk): add did:jwk support to did resolver

- demo/app/lib/views/credential_details.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/views/otp.dart
- demo/app/lib/views/scanner.dart
- demo/app/lib/widgets/credential_card.dart
- demo/app/lib/widgets/credential_metadata_card.dart
- demo/app/lib/widgets/credential_verified_information_view.dart
closes #190
https://user-images.githubusercontent.com/7862595/213407667-fa183f95-eb4d-4677-85e2-419e24be75a9.mov
> feat(app): Implement credential preview screen

- demo/app/ios/Runner/OpenID4VP.swift
- demo/app/ios/Runner/flutterPlugin.swift
Uploading latest_ios_recording.mov…
> fix(app): Update ios plugin with latest sdk changes

- pkg/openid4ci/errors.go
> refactor(sdk): Remove unused parse error codes

- demo/app/lib/assets/images/success.png
- demo/app/lib/views/credential_added.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/widgets/credential_card.dart
- demo/app/pubspec.yaml
> fix(app): Added added success page after pressing save credential button

- demo/app/lib/views/scanner.dart
- demo/app/lib/widgets/common_title_appbar.dart
Uploading close_icon.MP4…
closes #199
> fix(app): Add logic to go back to dashboard when press on cross icon

- cmd/wallet-sdk-gomobile/credential/inquirer.go
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- go.mod
- go.sum
- pkg/openid4vp/openid4vp.go
- test/integration/go.mod
- test/integration/go.sum
> chore(sdk): update aries and remove PEx workaround.

- demo/app/lib/scenarios/handle_openid_url.dart
closes #209
https://user-images.githubusercontent.com/7862595/214351970-65450d05-7a24-4750-bb50-d35c74bd7341.mov
> fix(app): Add the support to scan the qr code without pincode (otp)

- cmd/wallet-sdk-gomobile/docs/usage.md
> docs(sdk): refresh docs to reflect latest changes in sdk.

- demo/app/ios/Podfile.lock
- demo/app/ios/Runner/Info.plist
> feat(app): ios deep links

- demo/app/lib/views/settings.dart
https://user-images.githubusercontent.com/7862595/215026207-9e19a981-f452-4f1d-9d09-f06e5ce9da47.mov
> fix(app): Implement sign out option in the app

- cmd/wallet-sdk-gomobile/activitylogger/mem/mem.go
- cmd/wallet-sdk-gomobile/activitylogger/mem/mem_test.go
- cmd/wallet-sdk-gomobile/api/activitylogger.go
- cmd/wallet-sdk-gomobile/api/api.go
- cmd/wallet-sdk-gomobile/docs/packages.md
- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/openid4ci/interaction.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction_test.go
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp.go
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp_test.go
- cmd/wallet-sdk-gomobile/wrapper/activitylogwrapper.go
- cmd/wallet-sdk-gomobile/wrapper/activitylogwrapper_test.go
- demo/app/android/app/src/main/kotlin/walletsdk/openid4ci/OpenID4CI.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4vp/OpenID4VP.kt
- demo/app/ios/Runner/OpenID4VP.swift
- demo/app/ios/Runner/flutterPlugin.swift
- pkg/activitylogger/noop/noop.go
- pkg/activitylogger/noop/noop_test.go
- pkg/api/activitylogger.go
- pkg/api/api.go
- pkg/openid4ci/clientconfig.go
- pkg/openid4ci/models.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4vp/openid4vp.go
- pkg/openid4vp/openid4vp_test.go
- pkg/openid4vp/opts.go
- test/integration/openid4ci_test.go
- test/integration/openid4vp_test.go
- test/integration/pkg/setup/oidc4ci/oidc4ci_setup.go
> feat(sdk): Activity log

- demo/app/ios/Runner.xcodeproj/project.pbxproj
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/ios/Runner/kmsStore.swift
- demo/app/lib/main.dart
> fix(app): Pass the swift userdefault storage to local kms store

- demo/app/integration_test/openid4ci_test.dart
- scripts/flutter_test.sh
- test/integration/cli/main.go
> test(app): added integration tests for various DID types

- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- go.mod
- go.sum
- test/integration/fixtures/.env
- test/integration/fixtures/docker-compose.yml
- test/integration/fixtures/profile/profiles.json
- test/integration/go.mod
- test/integration/go.sum
- test/integration/openid4ci_test.go
> feat(sdk): integration test for selective disclosure.

- demo/app/android/app/build.gradle
- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/android/app/src/main/kotlin/walletsdk/kmsStorage/kmsStore.kt
> fix(app): Implement sharedpreference storage for android to inject to localkms

- test/integration/fixtures/.env
- test/integration/openid4vp_test.go
> test(sdk): OpenID4VP test case with SD-JWT enabled

- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- go.mod
- go.sum
- test/integration/fixtures/profile/profiles.json
- test/integration/go.mod
- test/integration/go.sum
- test/integration/openid4vp_test.go
> test(sdk): openid4vp using sd-jwt and limited disclosure

- cmd/wallet-sdk-gomobile/activitylogger/mem/mem_test.go
- cmd/wallet-sdk-gomobile/api/activitylogger.go
- cmd/wallet-sdk-gomobile/api/activitylogger_test.go
- cmd/wallet-sdk-gomobile/api/testdata/sample_activity.json
- cmd/wallet-sdk-gomobile/openid4ci/interaction_test.go
- cmd/wallet-sdk-gomobile/wrapper/activitylogwrapper.go
- test/integration/openid4ci_test.go
- test/integration/openid4vp_test.go
- gomobile Activity type now has methods on it for accessing various fields and parameters.
- Added serialize and parse functions.
> feat(sdk): Enhancements to the gomobile Activity type

- Makefile
- test/integration/expecteddisplaydata/drivers_license_issuer.json
- test/integration/fixtures/hydra-config/hydra_configure.sh
- test/integration/fixtures/profile/profiles.json
- test/integration/openid4ci_test.go
- test/integration/openid4vp_test.go
- test/integration/pkg/setup/oidc4ci/oidc4ci_setup.go
> test(sdk): added driver's license issuer and test flow

- cmd/wallet-sdk-gomobile/docs/usage.md
> docs(sdk): openid4vp - sdk usage update

- demo/app/android/app/src/main/AndroidManifest.xml
> fix(app): minor security issue on android.

- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- go.mod
- go.sum
- test/integration/go.mod
- test/integration/go.sum
- test/integration/loginconsent/go.mod
- test/integration/loginconsent/go.sum
- test/integration/webhook/go.mod
- test/integration/webhook/go.sum
> chore(sdk): updated to latest afgo

- test/integration/fixtures/.env
- test/integration/openid4ci_test.go
> chore(sdk): updated to latest vcs and removed workaround in tests

- scripts/flutter_test.sh
- test/integration/fixtures/profile/profiles.json
- test/integration/openid4vp_test.go
> test(sdk): added test for presenting one of the issued creds

- demo/app/ios/Runner.xcodeproj/project.pbxproj
- demo/app/ios/Runner/LocalActivityLogger.swift
- demo/app/ios/Runner/OpenID4VP.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/views/credential_details.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/widgets/credential_card.dart
This pr implements inmemory activity logger. Attached is the screenshot. 
Need to implement - pass in store implementation so that activity can be viewed even when app restarts #241
I need to spend some time to render json of activity properly as per the design which is missing yet
closes #211
> feat(app): Implement in memory activity logger

- cmd/wallet-sdk-gomobile/api/credentials.go
- cmd/wallet-sdk-gomobile/api/credentials_test.go
> feat(sdk): Add an ID() method to the VC type

- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- cmd/wallet-sdk-gomobile/openid4ci/interaction.go
- cmd/wallet-sdk-gomobile/openid4ci/interaction_test.go
- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4ci/OpenID4CI.kt
- demo/app/ios/Runner/flutterPlugin.swift
- pkg/common/errors.go
- pkg/common/jwt_signer.go
- pkg/common/jwt_signer_test.go
- pkg/openid4ci/clientconfig.go
- pkg/openid4ci/errors.go
- pkg/openid4ci/models.go
- pkg/openid4ci/openid4ci.go
- pkg/openid4ci/openid4ci_test.go
- test/integration/go.mod
- test/integration/go.sum
- test/integration/openid4ci_test.go
- test/integration/openid4vp_test.go
> refactor(sdk,app): unify jwt signing.

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4ci/OpenID4CI.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4vp/OpenID4VP.kt
> fix(app): Update kotlin with latest openid4vc resolve display and implement activity logger 

- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/openid4ci/displaydata.go
- cmd/wallet-sdk-gomobile/openid4ci/displaydata_test.go
- cmd/wallet-sdk-gomobile/openid4ci/resolve_test.go
- cmd/wallet-sdk-gomobile/openid4ci/testdata/issuer_metadata.json
- pkg/credentialschema/credentialdisplay.go
- pkg/credentialschema/models.go
- pkg/credentialschema/testdata/issuer_metadata.json
- pkg/internal/issuermetadata/testdata/sample_issuer_metadata.json
- pkg/openid4ci/testdata/sample_issuer_metadata.json
- test/integration/expecteddisplaydata/bank_issuer.json
- test/integration/expecteddisplaydata/did_ion_issuer.json
- test/integration/expecteddisplaydata/drivers_license_issuer.json
- test/integration/fixtures/profile/profiles.json
- test/integration/openid4ci_test.go
- test/integration/pkg/setup/oidc4ci/oidc4ci_setup.go
> feat(sdk): Add support for getting value type in claim display data

- demo/app/integration_test/openid4ci_test.dart
- scripts/flutter_test.sh
> test(app): added flutter tests for drivers license and multiple creds flow

- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/models/activity_data_object.dart
- demo/app/lib/services/storage_service.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/views/otp.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/views/settings.dart
- demo/app/lib/widgets/credential_verified_information_view.dart
https://user-images.githubusercontent.com/7862595/220245557-473c263b-eae4-4982-8960-3e11b88e3770.mov
> fix(app): Update to use store activity logger

- demo/app/lib/views/otp.dart
- demo/app/lib/views/presentation_preview.dart
> fix(app): Fix otp and preview sceen

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4ci/OpenID4CI.kt
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/views/credential_details.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/widgets/credential_verified_information_view.dart
> fix(app): Update kotlin plugin with latest changes

- docs/bestpractices.md
Currently contains just one best practice, but this document may be added to in the future.
> docs(sdk): Add best practices document

- demo/app/android/app/src/main/kotlin/walletsdk/WalletSDK.kt
The changes were lost during the androind refactoring PR. The orginal PR to add support is https://github.com/trustbloc/wallet-sdk/pull/276/files.
> fix(app): (Android) Add P-384 key suppport for did:jwk

- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp.go
- cmd/wallet-sdk-gomobile/openid4vp/openid4vp_test.go
- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4vp/OpenID4VP.kt
- demo/app/ios/Runner/OpenID4VP.swift
- demo/app/ios/Runner/flutterPlugin.swift
- pkg/openid4vp/openid4vp.go
- pkg/openid4vp/openid4vp_test.go
- test/integration/openid4vp_test.go
> feat(sdk): sign presentation using a VC subject DID

- cmd/wallet-sdk-gomobile/docs/usage.md
- demo/app/android/app/src/androidTest/kotlin/integration_test.kt
- demo/app/ios/Podfile.lock
- Fix android integration tests
- Update ios podfile
- Update usaged document date and commit
> fix(app): android integration tests

- demo/app/lib/main.dart
- demo/app/lib/models/credential_data.dart
- demo/app/lib/scenarios/handle_openid_url.dart
- demo/app/lib/views/credential_details.dart
- demo/app/lib/views/otp.dart
- demo/app/lib/views/presentation_preview_multi_cred.dart
- demo/app/lib/views/settings.dart
Also fixes the pin required false flow bug with the issuance.
> fix(app): Remove createDID on login and invoke while requesting credential

- cmd/wallet-sdk-gomobile/display/displaydata.go
- cmd/wallet-sdk-gomobile/display/displaydata_test.go
- cmd/wallet-sdk-gomobile/display/resolve_test.go
- cmd/wallet-sdk-gomobile/display/testdata/credential_university_degree.jsonld
- cmd/wallet-sdk-gomobile/display/testdata/issuer_metadata.json
- cmd/wallet-sdk-gomobile/docs/usage.md
- pkg/credentialschema/credentialdisplay.go
- pkg/credentialschema/credentialschema_test.go
- pkg/credentialschema/models.go
- pkg/credentialschema/testdata/credential_university_degree.jsonld
- pkg/credentialschema/testdata/issuer_metadata.json
- pkg/models/issuer/metadata.go
Note that the masking implementation only supports regex that specifies characters at the beginning of a string to mask.
> feat(sdk): Support for masking, raw ID, and pattern data in display

- cmd/wallet-sdk-gomobile/did/wellknown_test.go
- pkg/did/wellknown/wellknown_test.go
This resolves an issue where unit tests would fail if the remote server fails to respond as expected.
> fix(sdk): Switch remote server calls in unit test to local mock server

- Makefile
- scripts/prepare_integration_test_flutter.sh
- test/integration/fixtures/.env
> test(app): added health checks for docker containers

- cmd/wallet-sdk-gomobile/docs/usage.md
- pkg/openid4ci/errors.go
* Added error codes and troubleshooting tips for OpenID4CI, OpenID4VP, and DID APIs.
* Fixed a typo in one of the error codes.
> docs(sdk): Add error codes and troubleshooting tips

- demo/app/lib/views/credential_details.dart
- demo/app/lib/views/settings.dart
https://user-images.githubusercontent.com/7862595/225783852-93b89aff-5b04-4368-aa6b-b5fda5cb0239.mov
> fix(app): Add support for dev mode in the app

- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/scenarios/handle_openid_vp_flow.dart
> fix(app): Add the error handling for not matching cred found scenario

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/integration_test/openid4ci_test.dart
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/scenarios/handle_openid_issuance_flow.dart
- demo/app/lib/views/credential_details.dart
- demo/app/lib/views/otp.dart
- demo/app/lib/views/settings.dart
> fix(app): Add the version and show diddocument in the dev mode

- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- go.mod
- go.sum
- pkg/did/wellknown/wellknown.go
- test/integration/go.mod
- test/integration/go.sum
- Pull latest AFG changes
- Trim slash suffix from the url before passing to AFG function
> fix(sdk): DID Well-Known config validate

- scripts/prepare_integration_test_flutter.sh
Increased to match 60s set in SDK integration tests
> test(app): flutter test - increase startup sleep time

- demo/app/lib/views/credential_list.dart
https://user-images.githubusercontent.com/7862595/230235174-61f96be1-6544-4cc1-936f-d344a3102d12.mov
> fix(app): Add delete icon notification for deleting credentials

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4vp/OpenID4VP.kt
- demo/app/ios/Podfile
- demo/app/ios/Runner.xcodeproj/project.pbxproj
- demo/app/ios/Runner/OpenID4VP.swift
- demo/app/ios/Runner/WalletSDK.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/views/presentation_preview_multi_cred.dart
- demo/app/lib/views/settings.dart
> fix(app): Add verifier Display data changes in the app

- demo/app/lib/models/activity_logger.dart
- demo/app/lib/views/credential_details.dart
- demo/app/lib/views/credential_list.dart
> fix(app): Activity logger UI

- demo/app/ios/Runner/WalletSDK.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/models/activity_logger.dart
- demo/app/lib/services/storage_service.dart
- demo/app/lib/views/credential_details.dart
- demo/app/lib/views/credential_list.dart
Minor refactor to show the activities per user
> fix(app): Update to show activities per credential 

- demo/app/lib/views/credential_added.dart
- demo/app/lib/views/credential_shared.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/views/presentation_preview_multi_cred.dart
- demo/app/lib/views/presentation_preview_multi_cred_radio.dart
- demo/app/lib/widgets/success_card.dart
> fix(app): Update the success page to show the multi cred if shared multiple creds

- demo/app/lib/views/credential_details.dart
- demo/app/lib/views/custom_error.dart
- demo/app/lib/views/presentation_preview.dart
https://user-images.githubusercontent.com/7862595/235408295-32b3f338-8417-481c-9a63-d80c72dc8016.mov
> fix(app): Enable copy feature in the app 

- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/scenarios/handle_openid_vp_flow.dart
- demo/app/lib/views/otp.dart
- demo/app/lib/views/presentation_preview.dart
- Contains the fix for for pr card selection which was pointed out
> fix(app): Adding trace id to the error msg and fix for pr card selection

- demo/app/lib/scenarios/handle_openid_vp_flow.dart
> fix(app): Issue in the demo app with PR Card Verifier flow

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/integration_test/openid4ci_test.dart
- demo/app/ios/Podfile.lock
- demo/app/ios/Runner/OpenID4CI.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/scenarios/handle_openid_issuance_flow.dart
- demo/app/lib/scenarios/launched_external_url.dart
- demo/app/lib/views/auth_code_redirect.dart
- demo/app/pubspec.lock
- demo/app/pubspec.yaml
In order to test this flow you need real device as launching the url in the browser does not work in simulator. 
Also you would need to replace the client and redirect uri with the value - till 
I push the follow up pr to read the clientID and uri from the flutter environment variable. #423 
Also for error handling from the sdk #426 will be pushed as follow up pr
> feat(app): Auth code flow issuance ui

- cmd/wallet-sdk-gomobile/go.mod
- cmd/wallet-sdk-gomobile/go.sum
- go.mod
- go.sum
- test/integration/fixtures/.env
- test/integration/fixtures/profile/profiles.json
- test/integration/go.mod
- test/integration/go.sum
- test/integration/openid4ci_test.go
- test/integration/pkg/helpers/openid4ci.go
- test/integration/pkg/setup/oidc4ci/oidc4ci_setup.go
- test/integration/pkg/setup/oidc4vp/oidc4vp_setup.go
Also updated aries-framework-go version.
> feat(sdk): Update vc-rest version in BDD tests

- demo/app/ios/Runner/OpenID4CI.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/views/handle_redirect_uri.dart
> fix(app): Error handling support

- scripts/prepare_integration_test_flutter.sh
The CI fails with no image found, as a workaround added docker pull before starting the docker compose
> test(app): add docker pull command

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/converters/toFlutterTypes.kt
- demo/app/ios/Runner/coverters/toFlutterTypes.swift
- demo/app/lib/demo_method_channel.dart
- demo/app/lib/models/credential_data.dart
- demo/app/lib/scenarios/handle_openid_issuance_flow.dart
- demo/app/lib/scenarios/handle_openid_vp_flow.dart
- demo/app/lib/views/handle_redirect_uri.dart
- demo/app/lib/views/otp.dart
Selective disclosure flow and other flows works as expected now
> fix(app): Update the handle vp logic to support selective disclosure

- demo/app/lib/assets/issuerAuthFlowConfig.json
> feat(app): updated auth flow config with new profiles

- .gitignore
- Makefile
- cmd/wallet-sdk-js/Makefile
- cmd/wallet-sdk-js/package-lock.json
- cmd/wallet-sdk-js/package.json
- cmd/wallet-sdk-js/scripts/build_assets.sh
- cmd/wallet-sdk-js/webpack.config.js
> feat(sdk): added packaging for wallet-sdk-js

- .github/workflows/build.yml
- .gitignore
- cmd/wallet-sdk-js/package-lock.json
- cmd/wallet-sdk-js/package.json
- cmd/wallet-sdk-js/src/index.js
> feat(sdk): added npm package publishing for wallet-sdk-js

- .github/workflows/build.yml
- Makefile
- cmd/wallet-sdk-js/package-lock.json
- cmd/wallet-sdk-js/package.json
> fix(sdk): fixed wallet-sdk-js publishing script

- pkg/openid4vp/openid4vp.go
> fix(sdk): re-enable pEx v1 schema checking in openID4VP

- .github/workflows/build.yml
> fix(sdk): updated token for npm publishing

- demo/app/ios/Runner.xcodeproj/project.pbxproj
- demo/app/ios/Runner/WalletInitiatedOpenID4CI.swift
- demo/app/ios/Runner/WalletSDK.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/assets/walletConnectIssuerConfig.json
- demo/app/lib/models/connect_issuer_config.dart
- demo/app/lib/models/connect_issuer_config_value.dart
- demo/app/lib/services/config_service.dart
- demo/app/lib/views/dashboard.dart
- demo/app/lib/views/supported_credentials_list.dart
- demo/app/lib/views/wallet_initiated_connect.dart
- demo/app/lib/wallet_sdk/wallet_sdk_mobile.dart
- demo/app/lib/wallet_sdk/wallet_sdk_model.dart
- demo/app/pubspec.lock
- demo/app/pubspec.yaml
Early implementation, not fully functional yet
> feat(app): Wallet Initiated flow UI changes

- cmd/wallet-sdk-js/src/index.js
> fix(sdk): added missing parseResolvedDisplayData method

- Makefile
- demo/app/web/.npmrc
- demo/app/web/index.html
- demo/app/web/package-lock.json
- demo/app/web/package.json
- demo/app/web/script.js
> feat(app): integrating with wallet-sdk-js npm registry

- README.md
- cmd/wallet-sdk-js/docs/usage.md
> docs(sdk): added usage documentation for wallet-sdk-js

- Makefile
> fix(app): updated targets for demo web app

- cmd/wallet-sdk-js/Makefile
- cmd/wallet-sdk-js/jsinterop/agent_test.go
- cmd/wallet-sdk-js/jsinterop/jssupport/async_runner.go
- cmd/wallet-sdk-js/jsinterop/types/credential.go
- cmd/wallet-sdk-js/jsinterop/types/presex.go
- cmd/wallet-sdk-js/jsinterop/types/presex_test.go
- cmd/wallet-sdk-js/src/index.js
- demo/app/integration_test/openid4ci_test.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/views/presentation_preview_multi_cred.dart
- demo/app/lib/views/presentation_preview_multi_cred_radio.dart
- demo/app/lib/wallet_sdk/wallet_sdk_js.dart
- demo/app/lib/wallet_sdk/wallet_sdk_mobile.dart
- demo/app/lib/wallet_sdk/wallet_sdk_model.dart
- demo/app/pubspec.lock
- demo/app/web/index.html
- demo/app/web/script.js
https://github.com/trustbloc/wallet-sdk/assets/62515092/b4fa91e1-13a8-461c-aea8-007e99a5e39e
> feat(sdk,app): integration of openci4vp into the demo app.

- .github/workflows/release.yml
> feat(sdk): added release job for wallet-sdk-js

- demo/app/web/package-lock.json
- demo/app/web/package.json
> chore(app): updated wallet-sdk-js to latest

- demo/app/web/package-lock.json
- demo/app/web/package.json
> chore(app): updated to latest wallet-sdk-js

- demo/app/lib/views/otp.dart
> fix(app): fixed responsiveness bug in the otp screen

- demo/app/android/app/src/main/kotlin/walletsdk/WalletInitiatedOpenID4CI/WalletInitiatedOpenID4CI.kt
- demo/app/android/app/src/main/kotlin/walletsdk/WalletSDK.kt
- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4ci/OpenID4CI.kt
- demo/app/ios/Runner/WalletSDK.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/wallet_sdk/wallet_sdk_mobile.dart
> feat(app): Implement wallet initiate flow in android

- cmd/wallet-sdk-gomobile/docs/usage.md
- cmd/wallet-sdk-gomobile/openid4ci/issuermetadata_test.go
- cmd/wallet-sdk-gomobile/openid4ci/localizedissuerdisplay.go
- cmd/wallet-sdk-gomobile/openid4ci/testdata/sample_issuer_metadata.json
- pkg/models/issuer/metadata.go
> feat(sdk): Support for getting issuer logo from metadata (if available)

- Makefile
- images/demo/app/Dockerfile
> feat(app): added containerization for demo flutter app web

- .github/workflows/build.yml
> fix(app): fixed demo app image publishing

- demo/app/lib/views/supported_credentials_list.dart
> feat(app): Update supported credential UI in the wallet initiated flow

- .github/workflows/build.yml
- Makefile
- demo/app/web/package.json
> fix(app): updated demo app web docker image publishing logic

- .github/workflows/build.yml
> fix(app): switched token for ci job

- demo/app/lib/assets/walletInitiatedIssuerConfig.json
- demo/app/lib/scenarios/handle_openid_issuance_flow.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/views/credential_shared.dart
- demo/app/lib/widgets/credential_card.dart
- demo/app/lib/widgets/success_card.dart
> fix(app): Update the delete credential feature UI

- demo/app/web/package-lock.json
- demo/app/web/package.json
> chore(app): updated wallet-sdk to latest in demo app

- demo/app/web/package-lock.json
- demo/app/web/package.json
> chore(app): updated demo app to latest sdk

- demo/app/lib/assets/walletInitiatedIssuerConfig.json
> fix(app): Update the wallet initiated enviornemt to stg

- cmd/wallet-sdk-js/jsinterop/types/openid4ci.go
> feat(sdk): added support for issuer metadata in JS SDK

- demo/app/lib/wallet_sdk/wallet_sdk_js.dart
- demo/app/lib/wallet_sdk/wallet_sdk_model.dart
- demo/app/web/package-lock.json
- demo/app/web/package.json
- demo/app/web/script.js
> feat(app): added issuance preview screen for demo app web

- demo/app/lib/views/supported_credentials_list.dart
- demo/app/lib/views/wallet_initiated_connect.dart
> fix(app): Update the wallet initiate UI

- cmd/wallet-sdk-gomobile/display/displaydata.go
- cmd/wallet-sdk-gomobile/display/opts.go
- cmd/wallet-sdk-gomobile/display/resolve.go
- cmd/wallet-sdk-gomobile/display/resolve_test.go
- cmd/wallet-sdk-gomobile/docs/usage.md
- pkg/credentialschema/credentialdisplay.go
- pkg/credentialschema/credentialschema.go
- pkg/credentialschema/credentialschema_test.go
- pkg/credentialschema/models.go
- pkg/credentialschema/opts.go
> feat(sdk): Custom masking string option

- Makefile
> chore(app): updated targets to run demo web app in release mode

- cmd/wallet-sdk-js/jsinterop/agent.go
> fix(sdk): fixed claim value handling while parsing display data

- demo/app/lib/scenarios/handle_openid_issuance_flow.dart
- demo/app/lib/scenarios/handle_openid_vp_flow.dart
- demo/app/lib/views/custom_error.dart
- demo/app/lib/views/handle_redirect_uri.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/views/presentation_preview_multi_cred.dart
Main change is https://github.com/trustbloc/wallet-sdk/blob/676d63efe49a7d30728f94127f8ffcec003ed637/demo/app/lib/scenarios/handle_openid_vp_flow.dart#L35
> fix(app): Fix for the no credentials message while scanning QR code

- demo/app/analysis_options.yaml
- demo/app/integration_test/openid4ci_test.dart
- demo/app/lib/main.dart
- demo/app/lib/models/store_credential_data.dart
- demo/app/lib/scenarios/handle_openid_issuance_flow.dart
- demo/app/lib/scenarios/handle_openid_url.dart
- demo/app/lib/scenarios/handle_openid_vp_flow.dart
- demo/app/lib/services/config_service.dart
- demo/app/lib/services/storage_service.dart
- demo/app/lib/views/credential_details.dart
- demo/app/lib/views/credential_list.dart
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/views/credential_shared.dart
- demo/app/lib/views/handle_redirect_uri.dart
- demo/app/lib/views/issuance_preview.dart
- demo/app/lib/views/otp.dart
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/views/presentation_preview_multi_cred.dart
- demo/app/lib/views/presentation_preview_multi_cred_radio.dart
- demo/app/lib/views/settings.dart
- demo/app/lib/views/supported_credentials_list.dart
- demo/app/lib/views/wallet_initiated_connect.dart
- demo/app/lib/wallet_sdk/wallet_sdk_js.dart
- demo/app/lib/wallet_sdk/wallet_sdk_mobile.dart
- demo/app/lib/wallet_sdk/wallet_sdk_model.dart
- demo/app/lib/widgets/credential_metadata_card.dart
- demo/app/lib/widgets/credential_verified_information_view.dart
- demo/app/lib/widgets/success_card.dart
- demo/app/pubspec.lock
- demo/app/pubspec.yaml
> chore(app): linted dart code

- demo/app/lib/views/otp.dart
- demo/app/lib/widgets/loading_overlay.dart
https://github.com/trustbloc/wallet-sdk/assets/33902374/29b9853e-ad0b-4adf-9cff-198621434941
> feat(app): added loading overlay for the OTP screen

- .github/workflows/release.yml
> feat(app): added release job for the demo app web

- demo/app/lib/views/handle_redirect_uri.dart
This change avoid keep listening to all created subscription stream and hence no longer throw UKN2-200 data not found error so we don't need that ugly error check anymore.
> fix(app): Removing error check "UKN2-000" while handling redirect uri

- demo/app/web/package-lock.json
- demo/app/web/package.json
> chore(app): updated demo app web to latest sdk

- .github/workflows/build.yml
- .github/workflows/daily.yml
- test/integration/fixtures/.env
- test/integration/fixtures/docker-compose.yml
- test/integration/fixtures/profile/profiles.json
- test/integration/openid4ci_test.go
- update profiles to use ion instead of orb
- remove orb containers
> test(sdk): remove did:orb support

- .github/workflows/build.yml
- .github/workflows/release.yml
> chore(app): removed arm64 build and docker auth in release job

- demo/app/android/app/src/main/kotlin/walletsdk/WalletSDK.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4ci/OpenID4CI.kt
- demo/app/ios/Runner/OpenID4CI.swift
- demo/app/ios/Runner/WalletSDK.swift
> feat(app): Add support for DI proofs

- .github/workflows/build.yml
- .github/workflows/release.yml
- demo/app/web/package-lock.json
- demo/app/web/package.json
> fix(app): switched to using latest version of the sdk in demo app web

- .github/workflows/build.yml
> fix(app): fixed ci job dependency list

- cmd/wallet-sdk-gomobile/docs/usage.md
* Updated OpenID4CI examples to use the new DID creation pattern recently introduced.
* Made some other minor fixes and enhancements to the documentation.
> docs(sdk): Update OpenID4CI examples with new DID creation pattern

- demo/app/lib/scenarios/handle_openid_issuance_flow.dart
- demo/app/lib/views/issuance_preview.dart
> fix(app): Fix issuance preview screen

- demo/app/lib/assets/customScopes.json
- demo/app/lib/services/config_service.dart
> fix(app): Custom multiple scope update

- demo/app/pubspec.lock
- demo/app/pubspec.yaml
> fix(app): Fix the Type 'DecoderCallback' not found issue

- demo/app/integration_test/openid4ci_test.dart
- demo/app/ios/Runner/OpenID4CI.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/assets/images/error_icon.svg
- demo/app/lib/assets/images/tick-checked.svg
- demo/app/lib/views/issuance_preview.dart
- demo/app/lib/wallet_sdk/wallet_sdk_mobile.dart
- demo/app/lib/widgets/domain_verification_component.dart
- demo/app/pubspec.lock
- demo/app/pubspec.yaml
> feat(app): Add support for verify issuer api function in the app

- test/integration/openid4vp_test.go
> test(sdk): Add the test integration for multiple custom scope

- demo/app/android/app/src/androidTest/kotlin/integration_test.kt
- demo/app/integration_test/openid4ci_test.dart
- demo/app/ios/Podfile.lock
- demo/app/ios/Runner/Tests/IntegrationTest.swift
- demo/app/ios/Runner/flutterPlugin.swift
- scripts/android_test.sh
- scripts/flutter_test.sh
- scripts/ios_test.sh
- test/integration/openid4vp_test.go
> test(app): Upgrade flutter test with custom scope feature

- demo/app/ios/Runner/OpenID4CI.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/views/credential_preview.dart
- demo/app/lib/wallet_sdk/wallet_sdk_mobile.dart
> feat(app): Implement acknowledgement feature in app

- demo/app/android/app/src/main/kotlin/walletsdk/openid4ci/OpenID4CI.kt
- demo/app/ios/Runner/OpenID4CI.swift
> fix(app): Update acknowledge success function

- cmd/wallet-sdk-gomobile/docs/usage.md
- Add TOC
- Remove deprecated KeyReader and KeyWriter doc
> docs(sdk): remove deprecated api and restructure overall doc

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/converters/toFlutterTypes.kt
- demo/app/ios/Runner/coverters/toFlutterTypes.swift
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/wallet_sdk/wallet_sdk_model.dart
Updated the pr to show the deny reason as warning instead of blocking the flow
> feat(app): Handle the deny reason in  trust register in the app by showing error

- demo/app/android/app/src/main/kotlin/walletsdk/flutter/app/MainActivity.kt
- demo/app/android/app/src/main/kotlin/walletsdk/openid4vp/OpenID4VP.kt
- demo/app/ios/Runner/OpenID4VP.swift
- demo/app/ios/Runner/flutterPlugin.swift
- demo/app/lib/views/presentation_preview.dart
- demo/app/lib/views/presentation_preview_multi_cred.dart
- demo/app/lib/views/presentation_preview_multi_cred_radio.dart
- demo/app/lib/wallet_sdk/wallet_sdk_mobile.dart
> feat(app): Integrate no consent change in the app
